#!/usr/bin/env ruby
# encoding: utf-8
# Usage: yak gallerize
# Summary: create simple thumbnail gallery here

require 'clamp'
require 'fileutils'

Clamp do 
  option "--title", "TITLE", "Title to add to each page", default: "Image gallery"
  option "--force-thumbnail", :flag, "Force generation of thumbnails", default: false
  
  parameter "directory", "the directory to thumbnail", attribute_name: :directory
  
  def image_content(file)
    
    "<li><span class=\"helper\"></span><a href=\"#{file}\" class=\"thumbnail\"><img src=\"thumbs/#{file}\" /></a></li>"
  end
  
  def header(title, folder)
    <<-EOHTML
<html>
<head>
<style type="text/css">

img { 
  max-width: 100%; 
  vertical-align: middle;
}
ul {
  list-style-type: none;
  padding:0;
  margin:0;
}
li {
  display: inline-block;
  padding: 3px;
  margin: 5px;
  width: 200px;
  height: 200px;
}
.thumbnails {
  clear: both;
  text-align: center;
}

.thumbnail {
}

.helper {
  vertical-align: middle;
  display: inline-block;
  height: 100%;
}

h1 > small {
  color: #666;
  font-size: 0.6em;
}
</style>

</head>
<body>
<h1>
  #{title} - #{folder}
  <small>(click image for full resolution)</small>
</h1>
<div class="thumbnails">
<ul>
    EOHTML
  end
  
  def footer
    <<-EOHTML
</ul>
</div>
</body>
</html>
    EOHTML
  end
  
  def thumbnail(file)
    return if File.exists?("thumbs/#{file}") and !force_thumbnail?
    
    raise "Couldn't create thumbs directory" unless FileUtils.mkdir_p('thumbs')
    puts "Thumbnailing #{file}"
    `convert #{file} -resize 200x200 thumbs/#{file}`
  end
  
  def imagemagick_present?
    `which convert`
    $?.success?
  end
  
  def execute
    signal_usage_error "Skipping #{directory}, not a directory" unless File.directory?(directory)
    signal_usage_error "Imagemagick is not installed!" unless imagemagick_present?
    
    Dir.chdir(directory) do
      File.open('index.html', 'w') do |fp|
        fp << header(title, directory)
        
        Dir.glob('*.{jpg,JPG,png,PNG}') do |file|
          next if file[0] == ?. or file == 'index.html' or File.directory?(file)
          thumbnail(file)
          fp << image_content(file)
        end
        
        fp << footer()
      end
    end
  end
end